#!/bin/bash
workspaces=("University" "Current Directory" "General")
workspace=$(printf "%s\n" "${workspaces[@]}" | dmenu -i -p "Workspace type")
echo $workspace
case $workspace in
    "University")
        mount_mira
        i3-msg "exec --no-startup-id `st -T "scratchpad" bash -c 'nvim -o ~/University/Documents/*.org; bash'` -name __scratchpad" &
        ;;
    "Current Directory")
        i3-msg "exec --no-startup-id `st -T "scratchpad" bash -c 'nvim -o $PWD/*.org; bash'` -name __scratchpad" &
        ;;
    "General")
        i3-msg "exec --no-startup-id `st -T "scratchpad" bash -c 'nvim -o ~/Documents/*.org; bash'` -name __scratchpad" &
        ;;
esac
notify-send "Workspace setup"
