#!/bin/bash
workspaces=("University" "Current Directory" "General")
workspace=$(printf "%s\n" "${workspaces[@]}" | dmenu -i -p "Workspace type")
case $workspace in
    "University")
        mount_mira
        dir="~/University/Documents"
        ;;
    "Current Directory")
        dir=$PWD
        ;;
    "General")
        dir="~/Documents"
        ;;
esac
exec st -T 'scratchpad' bash -c "nvim -o $dir/*.org; bash" 2> /dev/null  & 
notify-send "$workspace Workspace setup"
